Image processing using numpy

In [3]:
import numpy as np

In [4]:
ones_arr = np.ones((5,5),dtype=int)
print(ones_arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [5]:
ones_arr * 255

array([[255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255]])

In [6]:
import matplotlib.pyplot as plt

In [7]:
from PIL import Image # python imaging library